name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache CMake files
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ qtbase5-dev qtdeclarative5-dev libopencv-dev libboost-all-dev

    - name: Remove build directory
      run: rm -rf build

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build --trace-expand --debug-output -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5

    - name: Build
      run: cmake --build build --verbose

    - name: Verify OpenCV installation
      run: |
        echo '#include <opencv2/opencv.hpp>' > test_opencv.cpp
        echo 'int main() { cv::Mat img; return 0; }' >> test_opencv.cpp
        g++ test_opencv.cpp -o test_opencv `pkg-config --cflags --libs opencv4`
        ./test_opencv
