name: Build and Package (Diagnostic)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: List initial directory contents
      run: |
        echo "Initial directory contents:"
        ls -la
        pwd

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ qtbase5-dev qtdeclarative5-dev libopencv-dev libboost-all-dev
    
    - name: Create build directory
      run: mkdir build
    
    - name: List directory contents after creating build
      run: |
        echo "Directory contents after creating build:"
        ls -la
        echo "Build directory contents:"
        ls -la build

    - name: Configure CMake
      run: cmake -S . -B build --trace-expand --debug-output -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt5
    
    - name: Build
      run: cmake --build build --verbose
    
    - name: List build directory contents after build
      run: |
        echo "Build directory contents after build:"
        ls -la build
    
    - name: Package with CPack
      run: cmake --build build --target package
    
    - name: Create ZIP Package
      run: zip -j build/PhotoWorkflow-1.0.0-win64.zip build/PhotoWorkflow-1.0.0-win64.* || echo "ZIP creation failed"
    
    - name: List final directory contents
      run: |
        echo "Final directory contents:"
        ls -la
        echo "Final build directory contents:"
        ls -la build || echo "Build directory not found"
    
    - name: Upload Package
      uses: actions/upload-artifact@v3
      with:
        name: PhotoWorkflow
        path: build/PhotoWorkflow-1.0.0-win64.zip
    
    - name: Upload Build Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: build-logs
        path: |
          build/CMakeFiles/CMakeOutput.log
          build/CMakeFiles/CMakeError.log

    - name: Upload Workspace
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: workspace
        path: .
