name: Build PhotoWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libboost-all-dev libopencv-dev python3
          python3 -m pip install aqtinstall

      - name: Install Qt
        run: |
          python3 -m aqt install-qt linux desktop 5.12.2 gcc_64 --outputdir /home/runner/work/PhotoWorkflow/Qt

      - name: List Installed Qt Directory
        run: |
          ls -R /home/runner/work/PhotoWorkflow/Qt

      - name: List Installed Qt 5.12.2 Directory
        run: |
          ls -R /home/runner/work/PhotoWorkflow/Qt/5.12.2/gcc_64

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_PREFIX_PATH="/home/runner/work/PhotoWorkflow/Qt/5.12.2/gcc_64/lib/cmake/Qt5"

      - name: Build
        run: |
          cmake --build build

      - name: List Build Directory
        run: |
          ls -R build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PhotoWorkflow
          path: build/
