name: Cross-Compile for Windows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ mingw-w64 nsis

    - name: Set up MXE (M cross environment)
      run: |
        sudo apt-get install -y software-properties-common
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
        sudo add-apt-repository "deb [arch=amd64] https://pkg.mxe.cc/repos/apt focal main"
        sudo apt-get update
        sudo apt-get install -y mxe-x86-64-w64-mingw32.static-qt5 mxe-x86-64-w64-mingw32.static-opencv mxe-x86-64-w64-mingw32.static-boost

    - name: Debug MXE installation
      run: |
        echo "MXE installation directory contents:"
        ls -R /usr/lib/mxe
        echo "Searching for mxe-conf.cmake:"
        find /usr/lib/mxe -name mxe-conf.cmake

    - name: Set MXE environment variables
      run: |
        echo "MXE_PREFIX=/usr/lib/mxe/usr/x86_64-w64-mingw32.static" >> $GITHUB_ENV
        echo "PATH=$PATH:/usr/lib/mxe/usr/bin" >> $GITHUB_ENV
        echo "MXE_TOOLCHAIN=$(find /usr/lib/mxe -name mxe-conf.cmake | head -n 1)" >> $GITHUB_ENV

    - name: Verify MXE setup
      run: |
        echo "MXE_PREFIX: $MXE_PREFIX"
        echo "PATH: $PATH"
        echo "MXE_TOOLCHAIN: $MXE_TOOLCHAIN"
        ls -l $MXE_PREFIX || echo "MXE_PREFIX directory not found"
        echo "Qt5 CMake files:"
        find $MXE_PREFIX -name "Qt5Config.cmake"
        echo "Boost CMake files:"
        find $MXE_PREFIX -name "BoostConfig.cmake"

    - name: Verify and copy icon
      run: |
        if [ -f "eab290ac-4e82-479f-b62e-9fb1d759a300.ico" ]; then
          echo "Icon file found"
          mkdir -p build
          cp eab290ac-4e82-479f-b62e-9fb1d759a300.ico build/
        else
          echo "Icon file not found"
          exit 1
        fi

    - name: Configure CMake for Windows
      run: |
        cmake -S . -B build \
        -DCMAKE_TOOLCHAIN_FILE=$MXE_TOOLCHAIN \
        -DCMAKE_FIND_ROOT_PATH=$MXE_PREFIX \
        -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
        -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
        -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
        -DCMAKE_C_COMPILER=$MXE_PREFIX/bin/x86_64-w64-mingw32.static-gcc \
        -DCMAKE_CXX_COMPILER=$MXE_PREFIX/bin/x86_64-w64-mingw32.static-g++ \
        -DCMAKE_MAKE_PROGRAM=/usr/bin/make

    - name: Build
      run: cmake --build build --config Release

    - name: Package with CPack
      run: |
        cd build
        cpack -G NSIS
        cd ..

    - name: List build directory contents
      run: |
        echo "Build directory contents:"
        ls -la build

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v4
      with:
        name: PhotoWorkflow-Windows-Installer
        path: build/PhotoWorkflow-*-Windows.exe
        if-no-files-found: error

    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-logs
        path: build/
        if-no-files-found: warn

    - name: Upload CMake Configuration
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cmake-config
        path: |
          build/CMakeCache.txt
          build/CMakeFiles/CMakeError.log
          build/CMakeFiles/CMakeOutput.log
        if-no-files-found: warn
