name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache CMake files
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
          build
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libopencv-dev libboost-all-dev

    - name: Remove build directory
      run: rm -rf build

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build --trace-expand --debug-output -DCMAKE_PREFIX_PATH=/opt/Qt/5.12.2/gcc_64

    - name: Build
      run: cmake --build build --verbose
