name: Build PhotoWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libboost-all-dev libopencv-dev python3
        python3 -m pip install aqtinstall

    - name: Install Qt 5.12.2
      run: |
        python3 -m aqt install-qt -O /opt/Qt linux desktop 5.12.2 gcc_64 -m qtcore qtgui qtwidgets

    - name: Set Qt environment variables
      run: |
        echo "/opt/Qt/5.12.2/gcc_64/bin" >> $GITHUB_PATH
        echo "QT_PLUGIN_PATH=/opt/Qt/5.12.2/gcc_64/plugins" >> $GITHUB_ENV
        echo "QML2_IMPORT_PATH=/opt/Qt/5.12.2/gcc_64/qml" >> $GITHUB_ENV
        echo "Qt5_DIR=/opt/Qt/5.12.2/gcc_64/lib/cmake/Qt5" >> $GITHUB_ENV

    - name: Configure CMake
      run:
