- name: Install Qt 5.12.2
  run: |
    python3 -m pip install aqtinstall
    python3 -m aqt install-qt -O /opt/Qt linux desktop 5.12.2 gcc_64 -m qtcore qtgui qtwidgets
- name: Set Qt environment variables
  run: |
    echo "/opt/Qt/5.12.2/gcc_64/bin" >> $GITHUB_PATH
    echo "QT_PLUGIN_PATH=/opt/Qt/5.12.2/gcc_64/plugins" >> $GITHUB_ENV
    echo "QML2_IMPORT_PATH=/opt/Qt/5.12.2/gcc_64/qml" >> $GITHUB_ENV
